In [21]:
# Dependencies
import csv
import json
import matplotlib.pyplot as plt
import requests
import pandas as pd
from pprint import pprint

In [46]:
data_file = "UR_KAN_pubs.csv"

In [49]:
data_file_pd = pd.read_csv(data_file)
data_file_pd["Publication Year"]= data_file_pd["Publication Year"].fillna(0.0).astype(int)
data_file_pd.head()

,Authors,Title,Journal Title,Volume,Issue,Beginning Page,Ending Page,DOI,Publication Date,Publication Year,...,Unnamed: 276,Unnamed: 277,Unnamed: 278,Unnamed: 279,Unnamed: 280,Unnamed: 281,Unnamed: 282,Unnamed: 283,Unnamed: 284,Unnamed: 285
0,"Mago, Shakun D.; Sheremeta, Roman M.",New Hampshire Effect: behavior in sequential a...,EXPERIMENTAL ECONOMICS,22,2,325,349,10.1007/s10683-018-9569-0,19-Jun,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Kotler, Philip; Manrai, Lalita A.; Lascu, Dana...",Influence of country and company characteristi...,INTERNATIONAL BUSINESS REVIEW,28,3,482,498,10.1016/j.ibusrev.2018.11.006,19-Jun,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Joshi, Piyush; Darr, Andrew J.; Skromne, Isaac",CDX4 regulates the progression of neural matur...,DEVELOPMENTAL BIOLOGY,449,2,132,142,10.1016/j.ydbio.2019.02.014,MAY 15 2019,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Park, Hyejin; McEachon, Joseph D., II; Pollock...",Synthesis and characterization of hydrogen per...,BIOORGANIC & MEDICINAL CHEMISTRY,27,10,2075,2082,10.1016/j.bmc.2019.04.003,MAY 15 2019,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Duer, M.; Schmidt, A.; Pybus, J. R.; Segarra, ...",Direct Observation of Proton-Neutron Short-Ran...,PHYSICAL REVIEW LETTERS,122,17,NaN,NaN,10.1103/PhysRevLett.122.172502,MAY 3 2019,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
UR_pubs = data_file_pd[["Authors", "Journal Title", "Publication Year"]]
UR_pubs.head()

,Authors,Journal Title,Publication Year
0,"Mago, Shakun D.; Sheremeta, Roman M.",EXPERIMENTAL ECONOMICS,2019
1,"Kotler, Philip; Manrai, Lalita A.; Lascu, Dana...",INTERNATIONAL BUSINESS REVIEW,2019
2,"Joshi, Piyush; Darr, Andrew J.; Skromne, Isaac",DEVELOPMENTAL BIOLOGY,2019
3,"Park, Hyejin; McEachon, Joseph D., II; Pollock...",BIOORGANIC & MEDICINAL CHEMISTRY,2019
4,"Duer, M.; Schmidt, A.; Pybus, J. R.; Segarra, ...",PHYSICAL REVIEW LETTERS,2019

In [51]:
journal_grouping = data_file_pd.groupby(["Journal Title"]).count()[["Title"]]
journal_grouping

                                                    Title
Journal Title
ABACUS-A JOURNAL OF ACCOUNTING FINANCE AND BUSI...      2
ABSTRACTS OF PAPERS OF THE AMERICAN CHEMICAL SO...    188
ACADEMIC THERAPY                                        1
ACADEMY OF MANAGEMENT ANNALS                            1
ACADEMY OF MANAGEMENT EXECUTIVE                         2
ACADEMY OF MANAGEMENT JOURNAL                           3
ACADEMY OF MANAGEMENT LEARNING & EDUCATION              1
ACADEMY OF MANAGEMENT PERSPECTIVES                      2
ACADEMY OF MANAGEMENT REVIEW                            7
ACCOUNTABILITY IN RESEARCH-POLICIES AND QUALITY...      5
ACCOUNTING HISTORIANS JOURNAL                           1
ACCOUNTING HORIZONS                                     2
ACCOUNTING REVIEW                                       1
ACM TRANSACTIONS ON ARCHITECTURE AND CODE OPTIM...      1
ACM TRANSACTIONS ON COMPUTATIONAL LOGIC                 1
ACM TRANSACTIONS ON PROGRAMMING LANGUAGES AND S...      2
ACS CATALYSIS                                           1
ACS CHEMICAL BIOLOGY                                    1
ACS MEDICINAL CHEMISTRY LETTERS                         1
ACS SENSORS                                             1
ACTA ANATOMICA                                          1
ACTA CRYSTALLOGRAPHICA SECTION F-STRUCTURAL BIO...      1
ACTA PHYSICA POLONICA B                                 2
ACTA ZOOLOGICA                                          1
ADDICTIVE BEHAVIORS                                     1
ADMINISTRATION & SOCIETY                                1
ADMINISTRATION AND POLICY IN MENTAL HEALTH AND ...      1
ADVANCES IN CONSUMER RESEARCH                           1
ADVANCES IN EXPERIMENTAL SOCIAL PSYCHOLOGY              1
AFRICA                                                  3
...                                                   ...
VIOLENCE AND VICTIMS                                    1
VIRGINIA JOURNAL OF INTERNATIONAL LAW                   1
VIRGINIA LAW REVIEW                                     4
VIRGINIA MAGAZINE OF HISTORY AND BIOGRAPHY             26
VIRGINIA QUARTERLY REVIEW                               3
VIRUS RESEARCH                                          1
WASHINGTON LAW REVIEW                                   4
WATER                                                   1
WATER AIR AND SOIL POLLUTION                            1
WATER RESEARCH                                          1
WEED SCIENCE                                            1
WESTERN HISTORICAL QUARTERLY                            1
WETLANDS                                                1
WILLIAM AND MARY QUARTERLY                             31
WISCONSIN LAW REVIEW                                    2
WOMENS HEALTH ISSUES                                    1
WOMENS STUDIES INTERNATIONAL FORUM                      1
WORD & IMAGE                                            2
WORK AND OCCUPATIONS                                    1
WORK EMPLOYMENT AND SOCIETY                             1
WORLD AFFAIRS                                           3
WORLD LITERATURE TODAY                                  1
YALE JOURNAL OF BIOLOGY AND MEDICINE                    1
YALE LAW JOURNAL                                        2
YEARBOOK FOR TRADITIONAL MUSIC                          1
YOUNG CHILDREN                                          1
YOUTH & SOCIETY                                         2
ZOOKEYS                                                 2
ZOOMORPHOLOGY                                           1
ZOOTAXA                                                13

[1700 rows x 1 columns]

In [55]:
journal_sort = journal_grouping.sort_values("Title", ascending=False)
journal_sort.head()

                                                    Title
Journal Title
ABSTRACTS OF PAPERS OF THE AMERICAN CHEMICAL SO...    188
PHYSICAL REVIEW C                                     145
FASEB JOURNAL                                         136
LIBRARY JOURNAL                                        70
PHYSICAL REVIEW LETTERS                                60

In [57]:
yearly_publications = data_file_pd.groupby(["Publication Year"]).count()[["Title"]]
yearly_publications

                  Title
Publication Year
0                     2
1976                 20
1977                 20
1978                 37
1979                 34
1980                 48
1981                 24
1982                 34
1983                 38
1984                 43
1985                 41
1986                 46
1987                 47
1988                 40
1989                 60
1990                 49
1991                 47
1992                 73
1993                 64
1994                 97
1995                 68
1996                 82
1997                 60
1998                 87
1999                102
2000                 83
2001                110
2002                 84
2003                119
2004                135
2005                140
2006                168
2007                183
2008                166
2009                179
2010                195
2011                175
2012                216
2013                223
2014                237
2015                236
2016                249
2017                239
2018                236
2019                 72

In [58]:
yearly_publications_per_journal = data_file_pd.groupby(["Publication Year","Journal Title"]).count()[["Title"]]
yearly_publications_per_journal

                                                                     Title
Publication Year Journal Title
1976             AMERICAN MATHEMATICAL MONTHLY                           1
                 COPEIA                                                  1
                 ELH-ENGLISH LITERARY HISTORY                            1
                 FEDERATION PROCEEDINGS                                  1
                 JOURNAL OF EXPERIMENTAL ZOOLOGY                         2
                 JOURNAL OF GENERAL PSYCHOLOGY                           1
                 JOURNAL OF PRESBYTERIAN HISTORY                         1
                 JOURNAL OF THE WEST                                     2
                 NEW-YORK HISTORICAL SOCIETY QUARTERLY                   1
                 PARLIAMENTARY AFFAIRS                                   1
                 RESOURCES FOR AMERICAN LITERARY STUDY                   1
                 SOUTHERN HUMANITIES REVIEW                              2
                 VIRGINIA MAGAZINE OF HISTORY AND BIOGRAPHY              5
1977             ABSTRACTS OF PAPERS OF THE AMERICAN CHEMICAL SO...      1
                 AMERICAN MATHEMATICAL MONTHLY                           1
                 AMERICAN POETRY REVIEW                                  3
                 AMERICAN SCIENTIST                                      1
                 AMERICAN ZOOLOGIST                                      1
                 BIOCHEMISTRY                                            1
                 ESPRIT CREATEUR                                         1
                 FOREIGN LANGUAGE ANNALS                                 1
                 INTERNATIONAL REVIEW OF HISTORY AND POLITICAL S...      1
                 JOURNAL OF EXPERIMENTAL ZOOLOGY                         1
                 JOURNAL OF SOUTHERN HISTORY                             3
                 MUSICAL QUARTERLY                                       1
                 PROCEEDINGS OF THE AMERICAN MATHEMATICAL SOCIETY        1
                 SMALL GROUP BEHAVIOR                                    1
                 TRANSACTIONS-AMERICAN GEOPHYSICAL UNION                 1
                 YALE JOURNAL OF BIOLOGY AND MEDICINE                    1
1978             ABSTRACTS OF PAPERS OF THE AMERICAN CHEMICAL SO...      2
...                                                                    ...
2019             JOURNAL OF APPLIED SOCIAL PSYCHOLOGY                    1
                 JOURNAL OF BRAND MANAGEMENT                             1
                 JOURNAL OF COSMOLOGY AND ASTROPARTICLE PHYSICS          1
                 JOURNAL OF ETHOLOGY                                     1
                 JOURNAL OF EXPERIMENTAL PSYCHOLOGY-GENERAL              1
                 JOURNAL OF EXPERIMENTAL PSYCHOLOGY-HUMAN PERCEP...      1
                 JOURNAL OF FINANCIAL AND QUANTITATIVE ANALYSIS          1
                 JOURNAL OF HOMOSEXUALITY                                1
                 JOURNAL OF NATURAL HISTORY                              1
                 JOURNAL OF PSYCHOPATHOLOGY AND BEHAVIORAL ASSES...      1
                 JOURNAL OF QUALITY TECHNOLOGY                           1
                 JOURNAL OF SOCIAL AND CLINICAL PSYCHOLOGY               1
                 JOURNAL OF THE ACADEMY OF MARKETING SCIENCE             1
                 JOURNAL OF THE GILDED AGE AND PROGRESSIVE ERA           1
                 JOURNAL OF THE HISTORY OF THE BEHAVIORAL SCIENCES       1
                 LEADERSHIP QUARTERLY                                    1
                 MOLECULAR PHYLOGENETICS AND EVOLUTION                   2
                 NANOMATERIALS                                           1
                 NATURE                                                  1
                 PHYSICAL REVIEW LETTERS                                 3
                 PHYSICS LETTERS B                                       2
                 PLOS ONE                                                1
                 PSYCHONOMIC BULLETIN & REVIEW                           1
                 QUARTERLY JOURNAL OF SPEECH                             1
                 RISK ANALYSIS                                           1
                 SCANDINAVIAN JOURNAL OF PSYCHOLOGY                      1
                 SEX ROLES                                               1
                 TETRAHEDRON                                             2
                 TEXAS LAW REVIEW                                        1
                 WILLIAM AND MARY QUARTERLY                              2

[3570 rows x 1 columns]